/**
 * OEM-Specific Techsheet Templates
 *
 * Defines document templates and formatting rules for different OEM vendors.
 * Each OEM has specific requirements for:
 * - Document sections and order
 * - Header/footer content
 * - Logo placement
 * - Required fields
 * - Language preferences
 */

import type {
  OEMVendor,
  TechsheetTemplate,
  OEMRuleSet,
} from '@/types/techniqueSheet';

// ============================================================================
// Template Definitions
// ============================================================================

export const OEM_TEMPLATES: Record<OEMVendor, TechsheetTemplate> = {
  GENERIC: {
    id: 'tpl-generic-001',
    name: 'Standard Techsheet',
    oemVendor: 'GENERIC',
    templatePath: '/templates/generic-techsheet.pdf',
    language: 'english',
    sections: [
      'header',
      'part-info',
      'material',
      'equipment',
      'calibration',
      'scan-parameters',
      'acceptance-criteria',
      'documentation',
      'approvals',
      'footer',
    ],
    headerText: 'ULTRASONIC INSPECTION TECHNIQUE SHEET',
    footerText: 'Generated by Scan-Master | Confidential',
  },

  GE: {
    id: 'tpl-ge-001',
    name: 'GE Aviation Techsheet',
    oemVendor: 'GE',
    templatePath: '/templates/ge-techsheet.pdf',
    language: 'english',
    sections: [
      'ge-header',
      'part-identification',
      'material-specification',
      'equipment-configuration',
      'calibration-block',
      'dac-tcg-curves',
      'scan-plan',
      'coverage-map',
      'acceptance-per-p23tf22',
      'operator-instructions',
      'level-iii-approval',
      'revision-history',
      'ge-footer',
    ],
    logoPath: '/logos/ge-aviation.png',
    headerText: 'GE AVIATION - ULTRASONIC INSPECTION PROCEDURE',
    footerText: 'Per GE Specification P23TF22 | CONFIDENTIAL - GE PROPRIETARY',
  },

  RR: {
    id: 'tpl-rr-001',
    name: 'Rolls-Royce Techsheet',
    oemVendor: 'RR',
    templatePath: '/templates/rr-techsheet.pdf',
    language: 'english',
    sections: [
      'rr-header',
      'document-control',
      'part-definition',
      'material-data',
      'equipment-list',
      'calibration-standard',
      'inspection-zones',
      'scan-parameters',
      'acceptance-criteria-rrp59000',
      'safety-critical-notes',
      'signoff-matrix',
      'rr-footer',
    ],
    logoPath: '/logos/rolls-royce.png',
    headerText: 'ROLLS-ROYCE - NDT INSPECTION TECHNIQUE',
    footerText: 'RRP 59000 Series Compliant | ROLLS-ROYCE CONFIDENTIAL',
  },

  PW: {
    id: 'tpl-pw-001',
    name: 'Pratt & Whitney Techsheet',
    oemVendor: 'PW',
    templatePath: '/templates/pw-techsheet.pdf',
    language: 'english',
    sections: [
      'pw-header',
      'sim-reference',
      'part-data',
      'material-properties',
      'ut-equipment',
      'calibration-block-pwa',
      'sim-curves',
      'patch-plan',
      'coverage-verification',
      'acceptance-pwa127',
      'inspector-certification',
      'qa-approval',
      'pw-footer',
    ],
    logoPath: '/logos/pratt-whitney.png',
    headerText: 'PRATT & WHITNEY - SONIC INSPECTION METHOD',
    footerText: 'Per PWA 127 / SIM Specification | P&W PROPRIETARY',
  },
};

// ============================================================================
// OEM Rule Sets (Placeholder values - to be filled with real specs)
// ============================================================================

export const OEM_RULE_SETS: Record<OEMVendor, OEMRuleSet> = {
  GENERIC: {
    vendorId: 'GENERIC',
    vendorName: 'Generic / Standard',
    version: '1.0',
    effectiveDate: '2024-01-01',
    specReference: 'AMS-STD-2154',

    coverageRequirements: {
      minCoverage: 100,
      overlapRequirement: 15,
      criticalZoneMultiplier: 1.0,
      edgeExclusion: 3,
    },

    frequencyConstraints: {
      min: 1.0,
      max: 15.0,
      preferred: [2.25, 5.0, 10.0],
    },

    approvedTransducers: [],
    approvedBlocks: [],

    calibrationRules: {
      interval: 8,
      temperatureCheckRequired: false,
      dacCurveRequired: true,
      tcgRequired: false,
      transferCorrectionMax: 6,
      periodicVerificationHours: 4,
    },

    documentationRules: {
      templateId: 'tpl-generic-001',
      requiredSections: ['part-info', 'equipment', 'calibration', 'acceptance-criteria'],
      approvalLevels: 1,
      language: 'english',
      revisionTracking: true,
    },

    warnings: [],
    notes: ['Standard AMS-STD-2154 requirements apply'],
  },

  GE: {
    vendorId: 'GE',
    vendorName: 'GE Aviation',
    version: '2.0',
    effectiveDate: '2024-06-01',
    specReference: 'GE P23TF22',

    coverageRequirements: {
      minCoverage: 100,
      overlapRequirement: 20,           // GE requires higher overlap
      criticalZoneMultiplier: 1.5,      // 150% coverage on critical zones
      edgeExclusion: 5,
    },

    frequencyConstraints: {
      min: 2.25,
      max: 10.0,
      preferred: [5.0, 10.0],           // GE prefers higher frequencies
    },

    approvedTransducers: [
      {
        id: 'ge-probe-001',
        manufacturer: 'Olympus',
        model: 'V310-SU',
        frequency: 5.0,
        diameter: 12.7,
        type: 'immersion',
        approved: true,
      },
      {
        id: 'ge-probe-002',
        manufacturer: 'Olympus',
        model: 'V312-SU',
        frequency: 10.0,
        diameter: 6.35,
        type: 'immersion',
        approved: true,
      },
    ],

    approvedBlocks: [
      {
        id: 'ge-block-001',
        type: 'flat_block',
        material: 'Ti-6Al-4V',
        fbhSizes: ['#1', '#2', '#3'],
        geometry: 'flat',
        approved: true,
      },
    ],

    calibrationRules: {
      interval: 4,                       // GE: Calibrate every 4 hours
      temperatureCheckRequired: true,    // GE requires temp monitoring
      dacCurveRequired: true,
      tcgRequired: true,                 // GE prefers TCG
      transferCorrectionMax: 4,          // Stricter: max 4dB transfer
      periodicVerificationHours: 2,      // Check every 2 hours
    },

    documentationRules: {
      templateId: 'tpl-ge-001',
      requiredSections: [
        'part-identification',
        'equipment-configuration',
        'calibration-block',
        'dac-tcg-curves',
        'scan-plan',
        'coverage-map',
        'acceptance-per-p23tf22',
        'level-iii-approval',
      ],
      approvalLevels: 2,                 // GE: Level II + Level III
      language: 'english',
      revisionTracking: true,
    },

    warnings: [
      'GE P23TF22 requires Level III approval for all titanium inspections',
      'Temperature monitoring mandatory - reject if ΔT > 5°C',
    ],
    notes: [
      'Ensure probe serial numbers match GE approved list',
      'DAC curves must be generated on part material',
    ],
  },

  RR: {
    vendorId: 'RR',
    vendorName: 'Rolls-Royce',
    version: '3.1',
    effectiveDate: '2024-03-15',
    specReference: 'RRP 59000',

    coverageRequirements: {
      minCoverage: 100,
      overlapRequirement: 25,           // RR: Highest overlap requirement
      criticalZoneMultiplier: 2.0,      // 200% on safety-critical
      edgeExclusion: 6,
    },

    frequencyConstraints: {
      min: 2.0,
      max: 15.0,
      preferred: [2.25, 5.0, 7.5, 10.0],
    },

    approvedTransducers: [
      {
        id: 'rr-probe-001',
        manufacturer: 'GE Sensing',
        model: 'Alpha',
        frequency: 5.0,
        diameter: 10.0,
        type: 'immersion',
        approved: true,
      },
    ],

    approvedBlocks: [
      {
        id: 'rr-block-001',
        type: 'flat_block',
        material: 'Inconel 718',
        fbhSizes: ['#1', '#2', '#3', '#5'],
        geometry: 'flat',
        approved: true,
      },
    ],

    calibrationRules: {
      interval: 4,
      temperatureCheckRequired: true,
      dacCurveRequired: true,
      tcgRequired: true,
      transferCorrectionMax: 3,          // RR: Strictest - max 3dB
      periodicVerificationHours: 2,
    },

    documentationRules: {
      templateId: 'tpl-rr-001',
      requiredSections: [
        'document-control',
        'part-definition',
        'equipment-list',
        'calibration-standard',
        'inspection-zones',
        'acceptance-criteria-rrp59000',
        'safety-critical-notes',
        'signoff-matrix',
      ],
      approvalLevels: 3,                 // RR: Three approval levels
      language: 'english',
      revisionTracking: true,
    },

    warnings: [
      'RRP 59000 requires safety-critical zone documentation',
      'All deviations require Engineering Review Board approval',
      'Dual-frequency inspection may be required for thick sections',
    ],
    notes: [
      'CSS 217 applies to compressor components',
      'RRES 90000 series for material acceptance',
    ],
  },

  PW: {
    vendorId: 'PW',
    vendorName: 'Pratt & Whitney',
    version: '4.2',
    effectiveDate: '2024-04-01',
    specReference: 'PWA 127',

    coverageRequirements: {
      minCoverage: 100,
      overlapRequirement: 20,
      criticalZoneMultiplier: 1.5,
      edgeExclusion: 5,
    },

    frequencyConstraints: {
      min: 2.25,
      max: 15.0,
      preferred: [5.0, 10.0, 15.0],
    },

    approvedTransducers: [
      {
        id: 'pw-probe-001',
        manufacturer: 'Olympus',
        model: 'V320-SU',
        frequency: 5.0,
        diameter: 19.0,
        type: 'immersion',
        approved: true,
      },
    ],

    approvedBlocks: [
      {
        id: 'pw-block-001',
        type: 'flat_block',
        material: 'Ti-6Al-4V',
        fbhSizes: ['#1', '#2', '#3'],
        geometry: 'flat',
        approved: true,
      },
    ],

    calibrationRules: {
      interval: 4,
      temperatureCheckRequired: true,
      dacCurveRequired: true,
      tcgRequired: false,                // PW uses DAC primarily
      transferCorrectionMax: 4,
      periodicVerificationHours: 2,
    },

    documentationRules: {
      templateId: 'tpl-pw-001',
      requiredSections: [
        'sim-reference',
        'part-data',
        'ut-equipment',
        'calibration-block-pwa',
        'sim-curves',
        'patch-plan',
        'acceptance-pwa127',
        'inspector-certification',
        'qa-approval',
      ],
      approvalLevels: 2,
      language: 'english',
      revisionTracking: true,
    },

    warnings: [
      'PWA 127 SIM procedures must be referenced',
      'Engine-specific SIM numbers required on techsheet',
    ],
    notes: [
      'SIM = Sonic Inspection Method',
      'Contact P&W Engineering for part-specific SIM numbers',
    ],
  },
};

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get template for OEM vendor
 */
export function getOEMTemplate(vendor: OEMVendor): TechsheetTemplate {
  return OEM_TEMPLATES[vendor] || OEM_TEMPLATES.GENERIC;
}

/**
 * Get rule set for OEM vendor
 */
export function getOEMRuleSet(vendor: OEMVendor): OEMRuleSet {
  return OEM_RULE_SETS[vendor] || OEM_RULE_SETS.GENERIC;
}

/**
 * Get all required sections for an OEM
 */
export function getRequiredSections(vendor: OEMVendor): string[] {
  const template = getOEMTemplate(vendor);
  return template.sections;
}

/**
 * Check if a section is required for an OEM
 */
export function isSectionRequired(vendor: OEMVendor, sectionId: string): boolean {
  const template = getOEMTemplate(vendor);
  return template.sections.includes(sectionId);
}

/**
 * Get calibration interval for OEM (in hours)
 */
export function getCalibrationInterval(vendor: OEMVendor): number {
  const rules = getOEMRuleSet(vendor);
  return rules.calibrationRules.interval;
}

/**
 * Get coverage requirements for OEM
 */
export function getCoverageRequirements(vendor: OEMVendor): {
  minCoverage: number;
  overlap: number;
  criticalMultiplier: number;
} {
  const rules = getOEMRuleSet(vendor);
  return {
    minCoverage: rules.coverageRequirements.minCoverage,
    overlap: rules.coverageRequirements.overlapRequirement,
    criticalMultiplier: rules.coverageRequirements.criticalZoneMultiplier,
  };
}

/**
 * Validate setup against OEM rules
 */
export function validateAgainstOEMRules(
  vendor: OEMVendor,
  frequency: number,
  coverage: number,
  transferCorrection: number
): { valid: boolean; errors: string[]; warnings: string[] } {
  const rules = getOEMRuleSet(vendor);
  const errors: string[] = [];
  const warnings: string[] = [];

  // Frequency check
  if (frequency < rules.frequencyConstraints.min) {
    errors.push(`Frequency ${frequency} MHz below ${vendor} minimum of ${rules.frequencyConstraints.min} MHz`);
  }
  if (frequency > rules.frequencyConstraints.max) {
    errors.push(`Frequency ${frequency} MHz exceeds ${vendor} maximum of ${rules.frequencyConstraints.max} MHz`);
  }
  if (!rules.frequencyConstraints.preferred.includes(frequency)) {
    warnings.push(`Frequency ${frequency} MHz is not a preferred ${vendor} frequency`);
  }

  // Coverage check
  if (coverage < rules.coverageRequirements.minCoverage) {
    errors.push(`Coverage ${coverage}% below ${vendor} requirement of ${rules.coverageRequirements.minCoverage}%`);
  }

  // Transfer correction check
  if (transferCorrection > rules.calibrationRules.transferCorrectionMax) {
    errors.push(`Transfer correction ${transferCorrection} dB exceeds ${vendor} limit of ${rules.calibrationRules.transferCorrectionMax} dB`);
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// ============================================================================
// Export
// ============================================================================

export default {
  OEM_TEMPLATES,
  OEM_RULE_SETS,
  getOEMTemplate,
  getOEMRuleSet,
  getRequiredSections,
  isSectionRequired,
  getCalibrationInterval,
  getCoverageRequirements,
  validateAgainstOEMRules,
};
